apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/seanpe-com
  - ../base/cloudbeaver
namespace: apps

images:
  - name: seanpe11/seanpe-com
    newName: seanpe11/seanpe-com
    newTag: "v1.0.2" 
